### ISSUE TITLE
Comparison with RStudio's `gt` package

### ISSUE THREAD

**Issue by greimel** [ronisbr/PrettyTables.jl#173]
There's a [pretty recent R package by RStudio to create pretty tables](https://github.com/rstudio/gt).

It seems to be pretty feature rich and well thought through. They introduce their own names for table parts. Here's a screenshot from the package README.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/6280307/180959285-b44af69c-53ff-42cd-9d49-2a6fd71efc74.png">

Most of the elements are already available in, or have been asked for `PrettyTables`.

- [x] Title
- [ ] Subtitle
- [x] Column labels ("headers")
- [ ] Spanner column label (FR #12)
- [x] Stubhead label ("row name header") 
- [ ] Row groups (with labels)
- [ ] Summary label, Summary cells (FR #115)
- [ ] Footnotes, source notes (FR #115)

Introducing *row groups* might be interesting for printing `GroupedDataFrame`s (cc @bkamins). Here's a screen shot from the [RStudio blog](https://www.rstudio.com/blog/great-looking-tables-gt-0-2/)

<img width="448" alt="image" src="https://user-images.githubusercontent.com/6280307/180964106-228e4a0e-f2fa-4b89-93a2-153e25697435.png">

**Comment by bkamins** [comment]
This will be conveniently done when we add metadata to DataAPI.jl (and DataFrames.jl)

**Comment by ronisbr** [comment]
Thank you very much for this information!

By the way, I will change what I called `row name` to `row label`, which seems much better :D

Everything seems doable to implement except the `spanned column label`. It is somewhat difficult to do in text backend.

**Comment by jariji** [comment]
This diagram is missing support for hierarchical row labels like [Pandas has](https://jakevdp.github.io/PythonDataScienceHandbook/03.05-hierarchical-indexing.html)

![image](https://user-images.githubusercontent.com/96840304/209209557-9cdc965d-6b82-41b7-9715-1e1529f3105a.png)

**Comment by bkamins** [comment]
I understand this is handled in the diagram above by groups.

**Comment by Dale-Black** [comment]
I am super keen on this gt Table equivalent in Julia. Based on this issue, it looks like this might already be possible with some elbow grease using PrettyTables and DataFrames? Do you know if this is true, and if so, are there any links that might help me get started?

**Comment by ronisbr** [comment]
> This diagram is missing support for hierarchical row labels like [Pandas has](https://jakevdp.github.io/PythonDataScienceHandbook/03.05-hierarchical-indexing.html)

I also agree with @bkamins that this feature is equivalent to row group.

> I am super keen on this gt Table equivalent in Julia. Based on this issue, it looks like this might already be possible with some elbow grease using PrettyTables and DataFrames? Do you know if this is true, and if so, are there any links that might help me get started?

You can have some of the features using PrettyTables.jl in text, HTML, and LaTeX. Is there any specific use case you have in mind?

**Comment by Dale-Black** [comment]
I have a bunch of small dataframes that I would like to group into a formatted table like the gt table diagram shows

**Comment by jariji** [comment]
RStudio has a new blog post on the design of gt: https://posit-dev.github.io/great-tables/blog/design-philosophy/
